services:
  # Backend API service
  - type: web
    name: usuaria-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn usuaria.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: DATABASE_URL
        fromDatabase:
          name: usuaria_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

  # Frontend static site
  - type: web
    name: usuaria-frontend
    env: static
    buildCommand: cd usuaria_flutter && flutter build web --release --dart-define=API_URL=https://usuaria-backend.onrender.com/api
    staticPublishPath: ./usuaria_flutter/build/web
    envVars:
      - key: API_URL
        value: https://usuaria-backend.onrender.com/api

databases:
  - name: usuaria_db
    databaseName: usuaria
    user: usuaria
