name: Deploy to GitHub Pages
on:
  push:
    branches: [ deployment ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: usuaria_flutter/build/web
          branch: gh-pages
